/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as CampaignIdRouteImport } from './routes/campaign.$id'
import { Route as V1CampaignsRouteImport } from './routes/v1.campaigns'
import { Route as V1VerifyClaimManifestRouteImport } from './routes/v1.verify-claim-manifest'
import { Route as V1CampaignsCampaignIdRouteImport } from './routes/v1.campaigns.$campaignId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignIdRoute = CampaignIdRouteImport.update({
  id: '/campaign/$id',
  path: '/campaign/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const V1CampaignsRoute = V1CampaignsRouteImport.update({
  id: '/v1/campaigns',
  path: '/v1/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const V1VerifyClaimManifestRoute = V1VerifyClaimManifestRouteImport.update({
  id: '/v1/verify-claim-manifest',
  path: '/v1/verify-claim-manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const V1CampaignsCampaignIdRoute = V1CampaignsCampaignIdRouteImport.update({
  id: '/$campaignId',
  path: '/$campaignId',
  getParentRoute: () => V1CampaignsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/publish': typeof PublishRoute
  '/verify': typeof VerifyRoute
  '/campaign/$id': typeof CampaignIdRoute
  '/v1/campaigns': typeof V1CampaignsRouteWithChildren
  '/v1/verify-claim-manifest': typeof V1VerifyClaimManifestRoute
  '/v1/campaigns/$campaignId': typeof V1CampaignsCampaignIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/publish': typeof PublishRoute
  '/verify': typeof VerifyRoute
  '/campaign/$id': typeof CampaignIdRoute
  '/v1/campaigns': typeof V1CampaignsRouteWithChildren
  '/v1/verify-claim-manifest': typeof V1VerifyClaimManifestRoute
  '/v1/campaigns/$campaignId': typeof V1CampaignsCampaignIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/publish': typeof PublishRoute
  '/verify': typeof VerifyRoute
  '/campaign/$id': typeof CampaignIdRoute
  '/v1/campaigns': typeof V1CampaignsRouteWithChildren
  '/v1/verify-claim-manifest': typeof V1VerifyClaimManifestRoute
  '/v1/campaigns/$campaignId': typeof V1CampaignsCampaignIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/publish'
    | '/verify'
    | '/campaign/$id'
    | '/v1/campaigns'
    | '/v1/verify-claim-manifest'
    | '/v1/campaigns/$campaignId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/publish'
    | '/verify'
    | '/campaign/$id'
    | '/v1/campaigns'
    | '/v1/verify-claim-manifest'
    | '/v1/campaigns/$campaignId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/publish'
    | '/verify'
    | '/campaign/$id'
    | '/v1/campaigns'
    | '/v1/verify-claim-manifest'
    | '/v1/campaigns/$campaignId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  PublishRoute: typeof PublishRoute
  VerifyRoute: typeof VerifyRoute
  CampaignIdRoute: typeof CampaignIdRoute
  V1CampaignsRoute: typeof V1CampaignsRouteWithChildren
  V1VerifyClaimManifestRoute: typeof V1VerifyClaimManifestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/$id': {
      id: '/campaign/$id'
      path: '/campaign/$id'
      fullPath: '/campaign/$id'
      preLoaderRoute: typeof CampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/campaigns': {
      id: '/v1/campaigns'
      path: '/v1/campaigns'
      fullPath: '/v1/campaigns'
      preLoaderRoute: typeof V1CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/verify-claim-manifest': {
      id: '/v1/verify-claim-manifest'
      path: '/v1/verify-claim-manifest'
      fullPath: '/v1/verify-claim-manifest'
      preLoaderRoute: typeof V1VerifyClaimManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/campaigns/$campaignId': {
      id: '/v1/campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/v1/campaigns/$campaignId'
      preLoaderRoute: typeof V1CampaignsCampaignIdRouteImport
      parentRoute: typeof V1CampaignsRoute
    }
  }
}

interface V1CampaignsRouteChildren {
  V1CampaignsCampaignIdRoute: typeof V1CampaignsCampaignIdRoute
}

const V1CampaignsRouteChildren: V1CampaignsRouteChildren = {
  V1CampaignsCampaignIdRoute: V1CampaignsCampaignIdRoute,
}

const V1CampaignsRouteWithChildren = V1CampaignsRoute._addFileChildren(
  V1CampaignsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  PublishRoute: PublishRoute,
  VerifyRoute: VerifyRoute,
  CampaignIdRoute: CampaignIdRoute,
  V1CampaignsRoute: V1CampaignsRouteWithChildren,
  V1VerifyClaimManifestRoute: V1VerifyClaimManifestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
